# Generated by Django 3.0.3 on 2020-02-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Voters',
        ),
    ]
